Repository GitCoffee-hackathon2025/hackathon-frontend, pull requests merged in 2025-08, with the labels that each got.

#30 FEAT: Estilização de página "Não encontrada" (#29)
  src/views/PaginaNaoEncontrada.vue
Labels: Estilização, Estrutura HTML

#27 Serviço de criptografia
  package-lock.json
  package.json
  src/security/CryptoService.ts
Labels: Dependências, Lógica

#43 FEAT: Página de usuário
  src/App.vue
  src/assets/cores.scss
  src/components/NavBarra.vue
  src/components/usuario-configuracoes-informacoes/PainelOpcoes.vue
  src/router/index.ts
  src/store/ClasseOpcoes.ts
  src/store/InformacoesLogado.ts
  src/store/userTypes.ts
  src/views/Usuario/PaginaUsuario.vue
  src/views/Usuario/assets/ItensGerenciamentoConta.ts
  src/views/Usuario/views/GerenciamentConta.vue
  src/views/Usuario/views/HistoricoDenuncias.vue
  src/views/Usuario/views/TermosPrivacidade.vue
Labels: Estilização, Estrutura HTML, Refatoração, Lógica
